server:
  port: 8187
  servlet:
    context-path: /customs-auth

spring:
  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:authbase;MODE=PostgreSQL
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/diploma_auth?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: diploma_team
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
#      ddl-auto: validate
      ddl-auto: update
  mvc:
    hiddenmethod:
      filter:
        enabled: true
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: false
#  liquibase:
#    change-log: db/changelog/db.changelog-master.xml
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    change-log: db/changelog/v-1.0/insert-default-users-roles.sql
#    change-log: db/changelog/db.changelog-master.sql
jwt:
  secret: 2mflkgei234lvmjrtkj39u14690bmu3o;ijeriu6m1ubm341!@$UFNheuwiysdtuq349
  lifetime: 3600000
